seed: 42
device: cuda

### WANDB ###
wandb:
  project_name: mil-test
  run_name: test-colab-AdamW_lr_3_03_w_d_0.01-random_sampler_batch-16_32_10-layers_3_3
  tags:
    - test

### DATA ###
data:
  test_batch_size: 1024

### SAMPLER ###
sampler_config:
  random: false
  fixed_config: # только используется, если random: False
    - 1
    - 1 

### MODEL ###
model_config:
  checkpoint_path: null
  init_conv:
    in_channels: 1
    out_channels: 16

  variable_block1:
    in_channels: 16
    out_channels: 16

  downsample_conv:
    in_channels: 16
    out_channels: 32
    stride: 2

  variable_block2:
    in_channels: 32
    out_channels: 32

  fc:
    in_features: 32
    out_features: 10
