seed: 42
device: cuda
epochs: 200
save_interval: 20
checkpoint_dir: /content/miltesttasks-task-nas_int-mid/artifacts/train/random_sampler/train-colab-200_epoches-bs_8192-AdamW_lr_3_03_w_d_0.01-random_sampler_each_batch-16_32_10

### DATA ###
data:
  train_batch_size: 8192
  val_batch_size: 64
  val_fraction: 0.15

### SAMPLER ###
sampler_config:
  random: True
  fixed_config: null # (2, 2)
  batch_mode: True

### OPTIMIZER ###
optimizer:
  name: AdamW # AdamW
  params:
    lr: 3.0e-03
    # momentum: 0.9
    weight_decay: 0.01

### MODEL ###
model_config:
  checkpoint_path: null
  init_conv:
    in_channels: 1
    out_channels: 16

  variable_block1:
    in_channels: 16
    out_channels: 16

  downsample_conv:
    in_channels: 16
    out_channels: 32
    stride: 2

  variable_block2:
    in_channels: 32
    out_channels: 32

  fc:
    in_features: 32
    out_features: 10
