seed: 42
device: cuda
epochs: 200
save_interval: 20
checkpoint_dir: /content/miltesttasks-task-nas_int-mid/artifacts/train/from_scratch

### WANDB ###
wandb:
  project_name: mil-test
  run_name: train-layers_1_1-colab-200_epoches-bs_8192-AdamW_lr_3_03_w_d_0.01-from_scratch-16_32_10
  tags:
    - trian

### DATA ###
data:
  train_batch_size: 8192
  val_batch_size: 1024
  val_fraction: 0.15

### SAMPLER ###
sampler_config:
  random: false
  fixed_config: # (2, 2)
    - 1
    - 1

### OPTIMIZER ###
optimizer:
  name: AdamW # SGD
  params:
    lr: 3.0e-03
    # momentum: 0.9
    weight_decay: 0.01

### MODEL ###
model_config:
  checkpoint_path: null
  init_conv:
    in_channels: 1
    out_channels: 16

  variable_block1:
    in_channels: 16
    out_channels: 16

  downsample_conv:
    in_channels: 16
    out_channels: 32
    stride: 2

  variable_block2:
    in_channels: 32
    out_channels: 32

  fc:
    in_features: 32
    out_features: 10
