python /content/miltesttasks-task-nas_int-mid/scripts/inference.py --config-file /content/miltesttasks-task-nas_int-mid/configs/test-config.yaml --output-file /content/miltesttasks-task-nas_int-mid/artifacts/test/random_sampler/result_1_1.csv --run-name test-colab-AdamW_lr_3_03_w_d_0.01-random_sampler_batch-32_64_10-layers_1_1 --layers-first 1 --layers-second 1
python /content/miltesttasks-task-nas_int-mid/scripts/inference.py --config-file /content/miltesttasks-task-nas_int-mid/configs/test-config.yaml --output-file /content/miltesttasks-task-nas_int-mid/artifacts/test/random_sampler/result_1_2.csv --run-name test-colab-AdamW_lr_3_03_w_d_0.01-random_sampler_batch-32_64_10-layers_1_2 --layers-first 1 --layers-second 2
python /content/miltesttasks-task-nas_int-mid/scripts/inference.py --config-file /content/miltesttasks-task-nas_int-mid/configs/test-config.yaml --output-file /content/miltesttasks-task-nas_int-mid/artifacts/test/random_sampler/result_1_3.csv --run-name test-colab-AdamW_lr_3_03_w_d_0.01-random_sampler_batch-32_64_10-layers_1_3 --layers-first 1 --layers-second 3

python /content/miltesttasks-task-nas_int-mid/scripts/inference.py --config-file /content/miltesttasks-task-nas_int-mid/configs/test-config.yaml --output-file /content/miltesttasks-task-nas_int-mid/artifacts/test/random_sampler/result_2_1.csv --run-name test-colab-AdamW_lr_3_03_w_d_0.01-random_sampler_batch-32_64_10-layers_2_1 --layers-first 2 --layers-second 1
python /content/miltesttasks-task-nas_int-mid/scripts/inference.py --config-file /content/miltesttasks-task-nas_int-mid/configs/test-config.yaml --output-file /content/miltesttasks-task-nas_int-mid/artifacts/test/random_sampler/result_2_2.csv --run-name test-colab-AdamW_lr_3_03_w_d_0.01-random_sampler_batch-32_64_10-layers_2_2 --layers-first 2 --layers-second 2
python /content/miltesttasks-task-nas_int-mid/scripts/inference.py --config-file /content/miltesttasks-task-nas_int-mid/configs/test-config.yaml --output-file /content/miltesttasks-task-nas_int-mid/artifacts/test/random_sampler/result_2_3.csv --run-name test-colab-AdamW_lr_3_03_w_d_0.01-random_sampler_batch-32_64_10-layers_2_3 --layers-first 2 --layers-second 3

python /content/miltesttasks-task-nas_int-mid/scripts/inference.py --config-file /content/miltesttasks-task-nas_int-mid/configs/test-config.yaml --output-file /content/miltesttasks-task-nas_int-mid/artifacts/test/random_sampler/result_3_1.csv --run-name test-colab-AdamW_lr_3_03_w_d_0.01-random_sampler_batch-32_64_10-layers_3_1 --layers-first 3 --layers-second 1
python /content/miltesttasks-task-nas_int-mid/scripts/inference.py --config-file /content/miltesttasks-task-nas_int-mid/configs/test-config.yaml --output-file /content/miltesttasks-task-nas_int-mid/artifacts/test/random_sampler/result_3_2.csv --run-name test-colab-AdamW_lr_3_03_w_d_0.01-random_sampler_batch-32_64_10-layers_3_2 --layers-first 3 --layers-second 2
python /content/miltesttasks-task-nas_int-mid/scripts/inference.py --config-file /content/miltesttasks-task-nas_int-mid/configs/test-config.yaml --output-file /content/miltesttasks-task-nas_int-mid/artifacts/test/random_sampler/result_3_3.csv --run-name test-colab-AdamW_lr_3_03_w_d_0.01-random_sampler_batch-32_64_10-layers_3_3 --layers-first 3 --layers-second 3